### ISSUE TITLE
Implement WebSocket Chat Server API

### ISSUE THREAD

**Issue by ValeryTretyak** [apeps/second#2]

**Comment by nikitaeverywhere** [comment]
See [readme API draft](https://github.com/apeps/second#client-server-websocket-api) for basic implementation. @NatalieTr, you can test this API from the browser console:

1. Run the server.
2. Copy/paste [this code](https://github.com/ZitRos/ws-radio/blob/master/Radio.js) to browser's console.
3. `let ws = new WebSocket("ws://localhost:8080"); let radio = new Radio(ws);`
4. At this point, you should receive a console message on the server saying that a new client is connected.
5. Test: `radio.listen("message", (msg) => console.log(msg))`, `radio.tell("message", { text: "This is test" })`, `radio.tell("config", { /* ... */ })`.

Must:
1. After client sends a message, all clients (including sender) receive this message back from the server (server broadcasts the message).
2. Each chat client can configure its name. After client sets the name, their messages broadcast with the appropriate name.

**Comment by nikitaeverywhere** [comment]
Done.
