### ISSUE TITLE
Implement WebSocket Chat Client API

### ISSUE THREAD

**Issue by ValeryTretyak** [apeps/second#3]

**Comment by nikitaeverywhere** [comment]
I've added a "very basic" [API description](https://github.com/apeps/second#client-server-websocket-api) to readme. Natalie is currently working on implementing this API on server side. Once it is ready, implement the client-side basic API (at least `"message"` tell/listen).

**Comment by nikitaeverywhere** [comment]
Server is ready, see [notes here](https://github.com/apeps/second/issues/2#issuecomment-343656540) of how to interact with the server.
