### ISSUE TITLE
Ch-2 Create new chat - back

### ISSUE THREAD

**Issue by ValeryTretyak** [apeps/second#6]

**Comment by nikitaeverywhere** [comment]
Using WebSockets, right? Ping @sidkoalex

**Comment by nikitaeverywhere** [comment]
Uno momento, me and Natalie will create WebSockets backend part and upload [my old pub-sub module](https://github.com/ZitRos/ws-radio) for convenience.

**Comment by ValeryTretyak** [comment]
Ok

**Comment by nikitaeverywhere** [comment]
Basic setup done, Natalie will create WebSocket server endpoints.
